<?php

namespace Database\Seeders;

use App\Models\Disease;
use Illuminate\Database\Seeder;

class DiseaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $diseases = [
            // Existing entries
            [
                'name' => 'Cassava Mosaic Disease',
                'code' => 'CMD-01',
                'scientific_name' => 'Begomovirus',
                'commodity_type' => 'crop',
                'description' => 'A viral disease causing leaf chlorosis, distortion, and significant yield loss in cassava crops.',
                'symptoms' => 'Yellow mosaic pattern on leaves, leaf curling, stunted growth, twisted leaflets.',
                'treatment' => 'No chemical cure. Remove and burn infected plants immediately.',
                'prevention' => 'Use disease-resistant cassava cuttings and manage whitefly vectors.',
                'severity' => 'high',
            ],
            [
                'name' => 'Maize Lethal Necrosis',
                'code' => 'MLN-02',
                'scientific_name' => 'MCMV + SCMV co-infection',
                'commodity_type' => 'crop',
                'description' => 'A severe disease resulting from combination of Maize Chlorotic Mottle Virus and Sugarcane Mosaic Virus.',
                'symptoms' => 'Drying of leaf margins, premature drying of ears, necrosis starting from leaf tips.',
                'treatment' => 'Destroy infected crop residues.',
                'prevention' => 'Crop rotation with non-cereal crops, vector control, clean certified seed.',
                'severity' => 'critical',
            ],
            [
                'name' => 'African Swine Fever',
                'code' => 'ASF-03',
                'scientific_name' => 'African swine fever virus (ASFV)',
                'commodity_type' => 'livestock',
                'description' => 'A highly contagious and deadly viral disease affecting domestic and wild pigs.',
                'symptoms' => 'High fever, loss of appetite, reddening of skin on ears/abdomen, respiratory distress, high mortality.',
                'treatment' => 'No treatment or vaccine exists. Strict quarantine and culling required.',
                'prevention' => 'Strict biosecurity, control pig movement, disinfect footwear/equipment.',
                'severity' => 'critical',
            ],
            [
                'name' => 'Foot and Mouth Disease',
                'code' => 'FMD-04',
                'scientific_name' => 'Aphthovirus',
                'commodity_type' => 'livestock',
                'description' => 'A severe, highly contagious viral disease of cloven-hoofed animals such as cattle, sheep, and goats.',
                'symptoms' => 'Fever, blisters/lesions on tongue, feet, and udder, severe lameness, excess salivation.',
                'treatment' => 'Supportive care and wound treatment to prevent secondary bacterial infections.',
                'prevention' => 'Routine vaccination, movement restriction, quarantine measures.',
                'severity' => 'high',
            ],
            [
                'name' => 'Fall Armyworm',
                'code' => 'FAW-05',
                'scientific_name' => 'Spodoptera frugiperda',
                'commodity_type' => 'crop',
                'description' => 'An insect pest that feeds on leaves and stems of crops, predominantly maize and sorghum.',
                'symptoms' => 'Ragged feeding holes on whorl leaves, frass (excrement) present inside the leaf whorls.',
                'treatment' => 'Apply registered botanical or synthetic insecticides early in infestation.',
                'prevention' => 'Early planting, push-pull technology, intercropping with legumes.',
                'severity' => 'medium',
            ],

            // Additional Crop Diseases
            [
                'name' => 'Cassava Brown Streak Disease',
                'code' => 'CBSD-06',
                'scientific_name' => 'Cassava brown streak virus (CBSV/UCBSV)',
                'commodity_type' => 'crop',
                'description' => 'A viral disease causing necrotic lesions on cassava roots and stems, leading to major yield and quality losses.',
                'symptoms' => 'Yellow chlorotic blotches on leaves, brown streaks on stems, dry corky necrotic lesions in roots.',
                'treatment' => 'No chemical cure. Rogue and destroy infected plants.',
                'prevention' => 'Use virus-free planting material, resistant varieties, and manage whitefly vectors.',
                'severity' => 'critical',
            ],
            [
                'name' => 'Cassava Bacterial Blight',
                'code' => 'CBB-07',
                'scientific_name' => 'Xanthomonas axonopodis pv. manihotis',
                'commodity_type' => 'crop',
                'description' => 'A bacterial disease causing leaf spots, blight, and wilt in cassava, especially in humid conditions.',
                'symptoms' => 'Angular water-soaked leaf spots, leaf blight, wilting, and "candle-stick" appearance after defoliation.',
                'treatment' => 'Remove and burn infected plants; copper-based bactericides may reduce spread.',
                'prevention' => 'Use clean cuttings, resistant varieties, crop rotation, and avoid working in wet fields.',
                'severity' => 'high',
            ],
            [
                'name' => 'Banana Xanthomonas Wilt',
                'code' => 'BXW-08',
                'scientific_name' => 'Xanthomonas campestris pv. musacearum',
                'commodity_type' => 'crop',
                'description' => 'A bacterial wilt disease of banana and enset that causes rapid plant death and total bunch loss.',
                'symptoms' => 'Yellowing and wilting of leaves, yellow bacterial ooze from cut pseudostem, premature fruit ripening.',
                'treatment' => 'No cure. Uproot and destroy entire infected mats.',
                'prevention' => 'Use clean tools, male bud removal, resistant varieties where available, and strict sanitation.',
                'severity' => 'critical',
            ],
            [
                'name' => 'Black Sigatoka',
                'code' => 'BSIG-09',
                'scientific_name' => 'Pseudocercospora fijiensis (Mycosphaerella fijiensis)',
                'commodity_type' => 'crop',
                'description' => 'A devastating fungal leaf spot disease of banana that reduces photosynthetic area and fruit yield.',
                'symptoms' => 'Dark brown to black streaks on leaves that expand into large necrotic lesions; premature leaf death.',
                'treatment' => 'Fungicide sprays (protectant and systemic) on a regular schedule.',
                'prevention' => 'Resistant cultivars, proper spacing, leaf pruning, and drainage improvement.',
                'severity' => 'high',
            ],
            [
                'name' => 'Panama Disease (Fusarium Wilt of Banana)',
                'code' => 'FOC-10',
                'scientific_name' => 'Fusarium oxysporum f. sp. cubense (including TR4)',
                'commodity_type' => 'crop',
                'description' => 'A soil-borne fungal wilt disease that colonizes the vascular system of banana plants, often fatal.',
                'symptoms' => 'Yellowing of older leaves, progressive wilting, vascular discoloration (reddish-brown) in pseudostem.',
                'treatment' => 'No effective chemical cure. Destroy infected plants and avoid replanting susceptible cultivars.',
                'prevention' => 'Use resistant varieties, quarantine, clean planting material, and soil health management.',
                'severity' => 'critical',
            ],
            [
                'name' => 'Banana Bunchy Top Disease',
                'code' => 'BBTD-11',
                'scientific_name' => 'Banana bunchy top virus (BBTV)',
                'commodity_type' => 'crop',
                'description' => 'A viral disease transmitted by aphids that severely stunts banana plants and prevents fruit production.',
                'symptoms' => 'Stunted growth, bunchy upright leaves with dark green streaks, narrow brittle leaves, no or poor fruiting.',
                'treatment' => 'No cure. Rogue and destroy infected plants immediately.',
                'prevention' => 'Use virus-free planting material, control banana aphid vectors, and remove alternative hosts.',
                'severity' => 'high',
            ],
            [
                'name' => 'Maize Streak Virus',
                'code' => 'MSV-12',
                'scientific_name' => 'Maize streak virus (Geminivirus)',
                'commodity_type' => 'crop',
                'description' => 'A widespread viral disease of maize transmitted by leafhoppers, causing severe yield reduction.',
                'symptoms' => 'Narrow chlorotic streaks parallel to leaf veins, stunted plants, poorly filled cobs.',
                'treatment' => 'No chemical cure. Destroy infected plants.',
                'prevention' => 'Resistant varieties, early planting, and control of Cicadulina leafhopper vectors.',
                'severity' => 'high',
            ],
            [
                'name' => 'Grey Leaf Spot of Maize',
                'code' => 'GLS-13',
                'scientific_name' => 'Cercospora zeina / Cercospora zeae-maydis',
                'commodity_type' => 'crop',
                'description' => 'A fungal foliar disease of maize that causes significant yield loss under warm, humid conditions.',
                'symptoms' => 'Rectangular grey to tan lesions parallel to leaf veins that coalesce and kill large leaf areas.',
                'treatment' => 'Foliar fungicides applied at early disease stages.',
                'prevention' => 'Resistant hybrids, crop residue management, and crop rotation.',
                'severity' => 'medium',
            ],
            [
                'name' => 'Northern Leaf Blight of Maize',
                'code' => 'NLB-14',
                'scientific_name' => 'Exserohilum turcicum',
                'commodity_type' => 'crop',
                'description' => 'A fungal disease producing large lesions on maize leaves, reducing photosynthesis and yield.',
                'symptoms' => 'Long elliptical grey-green to tan lesions with dark borders on leaves.',
                'treatment' => 'Fungicide applications when disease pressure is high.',
                'prevention' => 'Resistant varieties, residue management, and balanced fertilization.',
                'severity' => 'medium',
            ],
            [
                'name' => 'Rice Blast',
                'code' => 'RB-15',
                'scientific_name' => 'Magnaporthe oryzae',
                'commodity_type' => 'crop',
                'description' => 'One of the most destructive fungal diseases of rice worldwide, affecting leaves, nodes, and panicles.',
                'symptoms' => 'Diamond-shaped lesions with grey centers on leaves, neck rot, and blank grains.',
                'treatment' => 'Systemic fungicides applied at critical growth stages.',
                'prevention' => 'Resistant varieties, balanced nitrogen, and good water management.',
                'severity' => 'high',
            ],
            [
                'name' => 'Rice Yellow Mottle Virus',
                'code' => 'RYMV-16',
                'scientific_name' => 'Rice yellow mottle virus',
                'commodity_type' => 'crop',
                'description' => 'A highly contagious viral disease of rice in Africa transmitted by beetles and mechanical means.',
                'symptoms' => 'Yellow mottling of leaves, stunting, reduced tillering, and poor grain filling.',
                'treatment' => 'No cure. Rogue infected plants.',
                'prevention' => 'Resistant varieties, clean seed, and vector management.',
                'severity' => 'high',
            ],
            [
                'name' => 'Bacterial Leaf Blight of Rice',
                'code' => 'BLB-17',
                'scientific_name' => 'Xanthomonas oryzae pv. oryzae',
                'commodity_type' => 'crop',
                'description' => 'A bacterial disease causing leaf blight and yield loss in rice, especially under high humidity.',
                'symptoms' => 'Water-soaked lesions turning yellow then white from leaf tips and margins; kresek (seedling wilt).',
                'treatment' => 'Copper-based bactericides and removal of infected plants.',
                'prevention' => 'Resistant varieties, balanced nitrogen, and clean irrigation water.',
                'severity' => 'high',
            ],
            [
                'name' => 'Coffee Leaf Rust',
                'code' => 'CLR-18',
                'scientific_name' => 'Hemileia vastatrix',
                'commodity_type' => 'crop',
                'description' => 'A fungal disease that causes severe defoliation and yield decline in Arabica coffee.',
                'symptoms' => 'Orange-yellow powdery spots on the underside of leaves leading to premature leaf drop.',
                'treatment' => 'Copper and systemic fungicides applied preventively.',
                'prevention' => 'Resistant varieties, proper spacing, shade management, and nutrition.',
                'severity' => 'high',
            ],
            [
                'name' => 'Coffee Berry Disease',
                'code' => 'CBD-19',
                'scientific_name' => 'Colletotrichum kahawae',
                'commodity_type' => 'crop',
                'description' => 'A fungal disease attacking coffee berries, causing significant crop loss in highland areas.',
                'symptoms' => 'Dark sunken lesions on green berries that expand and mummify the fruit.',
                'treatment' => 'Protectant fungicides during flowering and berry development.',
                'prevention' => 'Resistant varieties, good drainage, and timely pruning.',
                'severity' => 'high',
            ],
            [
                'name' => 'Coffee Wilt Disease',
                'code' => 'CWD-20',
                'scientific_name' => 'Fusarium xylarioides (Gibberella xylarioides)',
                'commodity_type' => 'crop',
                'description' => 'A vascular fungal wilt disease that kills coffee trees, particularly Robusta.',
                'symptoms' => 'Wilting and drying of branches, yellowing leaves, and eventual death of the entire tree.',
                'treatment' => 'Uproot and burn infected trees; no chemical cure.',
                'prevention' => 'Resistant clones, strict sanitation of tools, and quarantine.',
                'severity' => 'critical',
            ],
            [
                'name' => 'Anthracnose of Cassava',
                'code' => 'CAD-21',
                'scientific_name' => 'Colletotrichum gloeosporioides',
                'commodity_type' => 'crop',
                'description' => 'A fungal disease causing cankers on stems and leaf spots in cassava.',
                'symptoms' => 'Oval dark lesions on stems, leaf spots, and dieback of shoots.',
                'treatment' => 'Fungicide sprays and removal of infected stems.',
                'prevention' => 'Clean planting material and good field sanitation.',
                'severity' => 'medium',
            ],
            [
                'name' => 'Late Blight of Potato/Tomato',
                'code' => 'LB-22',
                'scientific_name' => 'Phytophthora infestans',
                'commodity_type' => 'crop',
                'description' => 'A devastating oomycete disease of potato and tomato that can destroy entire crops rapidly.',
                'symptoms' => 'Water-soaked lesions on leaves and stems that turn brown/black; white sporulation under humid conditions; tuber rot.',
                'treatment' => 'Systemic and contact fungicides applied preventively and curatively.',
                'prevention' => 'Resistant varieties, certified seed, crop rotation, and proper spacing.',
                'severity' => 'critical',
            ],
            [
                'name' => 'Tomato Yellow Leaf Curl Virus',
                'code' => 'TYLCV-23',
                'scientific_name' => 'Tomato yellow leaf curl virus (Begomovirus)',
                'commodity_type' => 'crop',
                'description' => 'A whitefly-transmitted viral disease causing severe stunting and yield loss in tomato.',
                'symptoms' => 'Upward curling and yellowing of leaves, stunted growth, and reduced fruit set.',
                'treatment' => 'No cure. Remove infected plants.',
                'prevention' => 'Resistant varieties, whitefly control, and insect-proof netting.',
                'severity' => 'high',
            ],
            [
                'name' => 'Bean Common Mosaic Virus',
                'code' => 'BCMV-24',
                'scientific_name' => 'Bean common mosaic virus',
                'commodity_type' => 'crop',
                'description' => 'A seed-borne viral disease of common beans causing mosaic and yield reduction.',
                'symptoms' => 'Mosaic patterns, leaf curling, and stunting; dark green vein banding.',
                'treatment' => 'No chemical cure. Rogue infected plants.',
                'prevention' => 'Virus-free seed, resistant varieties, and aphid control.',
                'severity' => 'medium',
            ],
            [
                'name' => 'Sorghum Downy Mildew',
                'code' => 'SDM-25',
                'scientific_name' => 'Peronosclerospora sorghi',
                'commodity_type' => 'crop',
                'description' => 'An oomycete disease causing systemic infection and yield loss in sorghum and maize.',
                'symptoms' => 'Chlorotic stripes on leaves, white downy growth on underside, and stunted plants with sterile panicles.',
                'treatment' => 'Seed treatment with systemic fungicides.',
                'prevention' => 'Resistant varieties and clean seed.',
                'severity' => 'medium',
            ],
            [
                'name' => 'Wheat Stem Rust (Ug99)',
                'code' => 'WSR-26',
                'scientific_name' => 'Puccinia graminis f. sp. tritici (Ug99 race)',
                'commodity_type' => 'crop',
                'description' => 'A highly virulent fungal rust that threatens wheat production across Africa and beyond.',
                'symptoms' => 'Reddish-brown pustules on stems and leaves that rupture the epidermis.',
                'treatment' => 'Fungicide sprays in commercial fields.',
                'prevention' => 'Resistant varieties and surveillance.',
                'severity' => 'critical',
            ],
            [
                'name' => 'Sweet Potato Virus Disease',
                'code' => 'SPVD-27',
                'scientific_name' => 'Sweet potato feathery mottle virus + Sweet potato chlorotic stunt virus',
                'commodity_type' => 'crop',
                'description' => 'A complex viral disease causing severe yield loss in sweet potato.',
                'symptoms' => 'Chlorosis, leaf distortion, stunting, and reduced storage root size.',
                'treatment' => 'No cure. Use clean planting material.',
                'prevention' => 'Virus-free vines, resistant varieties, and vector management.',
                'severity' => 'high',
            ],
            [
                'name' => 'Yam Mosaic Virus',
                'code' => 'YMV-28',
                'scientific_name' => 'Yam mosaic virus',
                'commodity_type' => 'crop',
                'description' => 'A potyvirus causing mosaic and yield reduction in yam.',
                'symptoms' => 'Mosaic, chlorosis, leaf distortion, and reduced tuber size.',
                'treatment' => 'No chemical cure. Rogue infected plants.',
                'prevention' => 'Clean seed yams and resistant varieties.',
                'severity' => 'medium',
            ],
            [
                'name' => 'Groundnut Rosette Disease',
                'code' => 'GRD-29',
                'scientific_name' => 'Groundnut rosette virus complex',
                'commodity_type' => 'crop',
                'description' => 'A viral disease transmitted by aphids that causes severe stunting in groundnut.',
                'symptoms' => 'Rosetting (shortened internodes), chlorosis or dark green leaves, and poor pod set.',
                'treatment' => 'No cure. Remove infected plants.',
                'prevention' => 'Early planting, resistant varieties, and aphid control.',
                'severity' => 'high',
            ],
            [
                'name' => 'Citrus Canker',
                'code' => 'CC-30',
                'scientific_name' => 'Xanthomonas citri subsp. citri',
                'commodity_type' => 'crop',
                'description' => 'A bacterial disease causing lesions on leaves, stems, and fruit of citrus.',
                'symptoms' => 'Raised corky lesions with water-soaked margins on leaves, fruit, and twigs.',
                'treatment' => 'Copper sprays and pruning of infected twigs.',
                'prevention' => 'Resistant varieties, windbreaks, and quarantine.',
                'severity' => 'medium',
            ],
            [
                'name' => 'Anthracnose of Mango',
                'code' => 'AM-31',
                'scientific_name' => 'Colletotrichum gloeosporioides',
                'commodity_type' => 'crop',
                'description' => 'A fungal disease affecting mango flowers, leaves, and fruit, causing major post-harvest losses.',
                'symptoms' => 'Black spots on leaves and fruit, blossom blight, and fruit rot.',
                'treatment' => 'Fungicide sprays during flowering and fruit development.',
                'prevention' => 'Pruning for air flow, resistant varieties, and post-harvest treatment.',
                'severity' => 'medium',
            ],
            [
                'name' => 'Papaya Ringspot Virus',
                'code' => 'PRSV-32',
                'scientific_name' => 'Papaya ringspot virus',
                'commodity_type' => 'crop',
                'description' => 'A potyvirus transmitted by aphids that severely affects papaya production.',
                'symptoms' => 'Mosaic and distortion of leaves, ringspots on fruit, and stunted growth.',
                'treatment' => 'No cure. Destroy infected plants.',
                'prevention' => 'Resistant (transgenic) varieties, isolation, and aphid control.',
                'severity' => 'high',
            ],

            // Additional Livestock Diseases
            [
                'name' => 'Peste des Petits Ruminants',
                'code' => 'PPR-33',
                'scientific_name' => 'Peste des petits ruminants virus (Morbillivirus)',
                'commodity_type' => 'livestock',
                'description' => 'A highly contagious viral disease of sheep and goats causing high mortality.',
                'symptoms' => 'High fever, nasal and ocular discharge, mouth lesions, diarrhea, and pneumonia.',
                'treatment' => 'Supportive care; no specific antiviral treatment.',
                'prevention' => 'Vaccination, movement control, and quarantine of new animals.',
                'severity' => 'critical',
            ],
            [
                'name' => 'Contagious Bovine Pleuropneumonia',
                'code' => 'CBPP-34',
                'scientific_name' => 'Mycoplasma mycoides subsp. mycoides',
                'commodity_type' => 'livestock',
                'description' => 'A contagious bacterial disease of cattle causing severe pneumonia and high economic losses.',
                'symptoms' => 'Fever, coughing, labored breathing, nasal discharge, and loss of appetite.',
                'treatment' => 'Antibiotics in early stages; often ineffective in advanced cases.',
                'prevention' => 'Vaccination, movement restriction, and slaughter of infected animals in outbreaks.',
                'severity' => 'high',
            ],
            [
                'name' => 'Lumpy Skin Disease',
                'code' => 'LSD-35',
                'scientific_name' => 'Lumpy skin disease virus (Capripoxvirus)',
                'commodity_type' => 'livestock',
                'description' => 'A viral disease of cattle transmitted by biting insects, causing skin nodules and production losses.',
                'symptoms' => 'Fever, firm skin nodules, enlarged lymph nodes, and reduced milk yield.',
                'treatment' => 'Supportive care and treatment of secondary infections.',
                'prevention' => 'Vaccination and control of insect vectors.',
                'severity' => 'high',
            ],
            [
                'name' => 'Rift Valley Fever',
                'code' => 'RVF-36',
                'scientific_name' => 'Rift Valley fever virus (Phlebovirus)',
                'commodity_type' => 'livestock',
                'description' => 'A mosquito-borne viral zoonosis affecting sheep, goats, cattle, and humans.',
                'symptoms' => 'Fever, abortions in pregnant animals, high mortality in young lambs and kids, hepatic necrosis.',
                'treatment' => 'Supportive care only; no specific treatment.',
                'prevention' => 'Vaccination of livestock and mosquito control.',
                'severity' => 'critical',
            ],
            [
                'name' => 'Newcastle Disease',
                'code' => 'ND-37',
                'scientific_name' => 'Avian orthoavulavirus 1',
                'commodity_type' => 'livestock',
                'description' => 'A highly contagious viral disease of poultry causing high mortality in unvaccinated flocks.',
                'symptoms' => 'Respiratory distress, nervous signs (twisted necks), green diarrhea, and sudden death.',
                'treatment' => 'No specific treatment; supportive care and secondary infection control.',
                'prevention' => 'Regular vaccination and strict biosecurity.',
                'severity' => 'critical',
            ],
            [
                'name' => 'Infectious Bursal Disease (Gumboro)',
                'code' => 'IBD-38',
                'scientific_name' => 'Infectious bursal disease virus',
                'commodity_type' => 'livestock',
                'description' => 'A viral disease of young chickens that destroys the bursa of Fabricius and causes immunosuppression.',
                'symptoms' => 'Depression, ruffled feathers, diarrhea, and high mortality in chicks 3–6 weeks old.',
                'treatment' => 'Supportive care; no specific antiviral.',
                'prevention' => 'Vaccination of breeders and chicks, and good biosecurity.',
                'severity' => 'high',
            ],
            [
                'name' => 'Highly Pathogenic Avian Influenza',
                'code' => 'HPAI-39',
                'scientific_name' => 'Influenza A virus (H5/H7 subtypes)',
                'commodity_type' => 'livestock',
                'description' => 'A severe viral disease of poultry with high mortality and zoonotic potential.',
                'symptoms' => 'Sudden death, respiratory distress, cyanosis of comb and wattles, and neurological signs.',
                'treatment' => 'No treatment; stamping-out policy usually applied.',
                'prevention' => 'Biosecurity, surveillance, and vaccination in some countries.',
                'severity' => 'critical',
            ],
            [
                'name' => 'Contagious Caprine Pleuropneumonia',
                'code' => 'CCPP-40',
                'scientific_name' => 'Mycoplasma capricolum subsp. capripneumoniae',
                'commodity_type' => 'livestock',
                'description' => 'A highly contagious bacterial pneumonia of goats with high mortality.',
                'symptoms' => 'Fever, coughing, nasal discharge, labored breathing, and rapid death.',
                'treatment' => 'Antibiotics (tetracyclines, macrolides) if treated early.',
                'prevention' => 'Vaccination and strict movement control.',
                'severity' => 'high',
            ],
            [
                'name' => 'Sheep and Goat Pox',
                'code' => 'SGP-41',
                'scientific_name' => 'Capripoxvirus',
                'commodity_type' => 'livestock',
                'description' => 'A viral disease causing pox lesions and production losses in sheep and goats.',
                'symptoms' => 'Fever, skin nodules and pustules, respiratory distress, and high mortality in young animals.',
                'treatment' => 'Supportive care and treatment of secondary infections.',
                'prevention' => 'Vaccination and quarantine.',
                'severity' => 'high',
            ],
            [
                'name' => 'Anthrax',
                'code' => 'ANTH-42',
                'scientific_name' => 'Bacillus anthracis',
                'commodity_type' => 'livestock',
                'description' => 'A bacterial zoonotic disease causing sudden death in cattle, sheep, goats, and other animals.',
                'symptoms' => 'Sudden death, bleeding from orifices, bloating, and incomplete rigor mortis.',
                'treatment' => 'Antibiotics if treated very early; usually too late.',
                'prevention' => 'Annual vaccination in endemic areas and proper carcass disposal.',
                'severity' => 'critical',
            ],
            [
                'name' => 'Brucellosis',
                'code' => 'BRU-43',
                'scientific_name' => 'Brucella abortus / B. melitensis',
                'commodity_type' => 'livestock',
                'description' => 'A bacterial zoonosis causing abortion and infertility in cattle, goats, and sheep.',
                'symptoms' => 'Late-term abortions, retained placenta, orchitis in males, and reduced fertility.',
                'treatment' => 'Long-term antibiotic therapy; often not practical in livestock.',
                'prevention' => 'Vaccination, testing, and culling of infected animals.',
                'severity' => 'high',
            ],
            [
                'name' => 'Trypanosomiasis (Nagana)',
                'code' => 'TRY-44',
                'scientific_name' => 'Trypanosoma congolense / T. vivax / T. brucei',
                'commodity_type' => 'livestock',
                'description' => 'A protozoan disease transmitted by tsetse flies causing chronic wasting in cattle and other livestock.',
                'symptoms' => 'Intermittent fever, anemia, progressive weight loss, and enlarged lymph nodes.',
                'treatment' => 'Trypanocidal drugs (diminazene, isometamidium).',
                'prevention' => 'Tsetse control, resistant breeds, and prophylactic treatment.',
                'severity' => 'high',
            ],
            [
                'name' => 'East Coast Fever',
                'code' => 'ECF-45',
                'scientific_name' => 'Theileria parva',
                'commodity_type' => 'livestock',
                'description' => 'A tick-borne protozoan disease of cattle causing high mortality in susceptible animals.',
                'symptoms' => 'High fever, enlarged lymph nodes, respiratory distress, and death within days.',
                'treatment' => 'Buparvaquone and supportive care if treated early.',
                'prevention' => 'Tick control, immunization (infection-and-treatment method), and resistant breeds.',
                'severity' => 'critical',
            ],
            [
                'name' => 'Blackleg',
                'code' => 'BL-46',
                'scientific_name' => 'Clostridium chauvoei',
                'commodity_type' => 'livestock',
                'description' => 'An acute bacterial disease of cattle and sheep causing sudden death and muscle necrosis.',
                'symptoms' => 'Sudden lameness, swelling of muscles (often crepitant), fever, and rapid death.',
                'treatment' => 'High-dose penicillin if treated at the earliest stage.',
                'prevention' => 'Vaccination of young stock and proper disposal of carcasses.',
                'severity' => 'high',
            ],
            [
                'name' => 'Fowl Typhoid',
                'code' => 'FT-47',
                'scientific_name' => 'Salmonella Gallinarum',
                'commodity_type' => 'livestock',
                'description' => 'A bacterial septicemic disease of poultry causing high mortality in growing and adult birds.',
                'symptoms' => 'Depression, ruffled feathers, diarrhea, and sudden death; pale combs.',
                'treatment' => 'Antibiotics may reduce mortality but do not eliminate carriers.',
                'prevention' => 'Vaccination, biosecurity, and sourcing from clean flocks.',
                'severity' => 'high',
            ],
            [
                'name' => 'Coccidiosis (Poultry)',
                'code' => 'COC-48',
                'scientific_name' => 'Eimeria spp.',
                'commodity_type' => 'livestock',
                'description' => 'A protozoan intestinal disease of chickens and other poultry causing diarrhea and poor growth.',
                'symptoms' => 'Bloody or mucoid diarrhea, ruffled feathers, weight loss, and high mortality in young birds.',
                'treatment' => 'Anticoccidial drugs (toltrazuril, amprolium, etc.).',
                'prevention' => 'Coccidiostats in feed, good litter management, and vaccination.',
                'severity' => 'medium',
            ],
            [
                'name' => 'Mastitis (Bovine)',
                'code' => 'MAS-49',
                'scientific_name' => 'Staphylococcus aureus / Streptococcus agalactiae / E. coli etc.',
                'commodity_type' => 'livestock',
                'description' => 'Inflammation of the mammary gland in dairy cattle caused by various bacteria, reducing milk quality and quantity.',
                'symptoms' => 'Swollen, hot, painful udder; abnormal milk (clots, watery); reduced yield.',
                'treatment' => 'Intramammary antibiotics and anti-inflammatories based on culture results.',
                'prevention' => 'Good milking hygiene, teat dipping, dry-cow therapy, and proper nutrition.',
                'severity' => 'medium',
            ],
            [
                'name' => 'Rabies',
                'code' => 'RAB-50',
                'scientific_name' => 'Rabies virus (Lyssavirus)',
                'commodity_type' => 'livestock',
                'description' => 'A fatal viral zoonosis transmitted by the bite of infected animals, affecting all mammals including livestock.',
                'symptoms' => 'Behavioral changes, aggression or paralysis, excessive salivation, and death.',
                'treatment' => 'No effective treatment once clinical signs appear.',
                'prevention' => 'Vaccination of dogs and livestock in endemic areas; avoid contact with wildlife.',
                'severity' => 'critical',
            ],
        ];

        foreach ($diseases as $diseaseData) {
            Disease::updateOrCreate(
                ['code' => $diseaseData['code']],
                $diseaseData
            );
        }
    }
}